import { and, desc, eq, lt, or } from "drizzle-orm";
import { categories, db, integrations, offers, outboxEvents, publications, routineExecutions, routines, stores } from "@promimi/database";
export const workerRepository = {
  async automationPaused() { const control = await db.query.integrations.findFirst({ where: eq(integrations.provider, "automation") }); return Boolean(control && !control.enabled); },
  publication: (id: string) => db.query.publications.findFirst({ where: eq(publications.id, id), with: { offer: { with: { store: true } } } }), integration: (provider: string) => db.query.integrations.findFirst({ where: eq(integrations.provider, provider) }),
  delivered: (id: string, result: { status: "SENT" | "FAILED" | "PENDING" | "PAUSED"; error?: string; externalId?: string }, attempts: number) => db.update(publications).set({ status: result.status, error: result.error ?? null, externalId: result.externalId ?? null, attempts, sentAt: result.status === "SENT" ? new Date() : null, updatedAt: new Date() }).where(eq(publications.id, id)),
  deliveryFailed: (id: string, attempts: number, error: string) => db.update(publications).set({ status: "FAILED", attempts, error, updatedAt: new Date() }).where(eq(publications.id, id)),
  retryablePublications: () => db.select({ id: publications.id }).from(publications).where(or(eq(publications.status, "PENDING"), and(eq(publications.status, "FAILED"), lt(publications.updatedAt, new Date(Date.now() - 5 * 60_000))))).orderBy(desc(publications.createdAt)).limit(100),
  expireOffers: () => db.update(offers).set({ status: "EXPIRED", updatedAt: new Date() }).where(and(eq(offers.status, "PUBLISHED"), lt(offers.expiresAt, new Date()))),
  scheduledRoutines: () => db.select({ id: routines.id, enabled: routines.enabled, scheduleCron: routines.scheduleCron }).from(routines), queuedExecutions: () => db.select({ id: routineExecutions.id, routineId: routineExecutions.routineId }).from(routineExecutions).where(eq(routineExecutions.status, "QUEUED")).limit(100)
  ,routine: (id: string) => db.query.routines.findFirst({ where: eq(routines.id, id) }), execution: (id: string) => db.query.routineExecutions.findFirst({ where: eq(routineExecutions.id, id) }), startExecution: (routineId: string) => db.insert(routineExecutions).values({ routineId, status: "RUNNING", startedAt: new Date() }).returning(), executionStatus: (id: string, status: "RUNNING" | "PAUSED" | "SUCCEEDED" | "FAILED", values: Record<string, unknown> = {}) => db.update(routineExecutions).set({ status, ...values }).where(eq(routineExecutions.id, id)), enabledIntegrations: () => db.select().from(integrations).where(eq(integrations.enabled, true)), offerBySource: (sourceUrl: string) => db.query.offers.findFirst({ where: eq(offers.sourceUrl, sourceUrl) }), refreshOffer: (id: string, values: Partial<typeof offers.$inferInsert>) => db.update(offers).set({ ...values, updatedAt: new Date() }).where(eq(offers.id, id)), store: (slug: string) => db.query.stores.findFirst({ where: eq(stores.slug, slug) }), category: (slug: string) => db.query.categories.findFirst({ where: eq(categories.slug, slug) }),
  createAutomatedOffer: (value: typeof offers.$inferInsert, destinations: string[]) => db.transaction(async tx => { const [offer] = await tx.insert(offers).values(value).returning(); if (destinations.length) { const created = await tx.insert(publications).values(destinations.map(destination => ({ offerId: offer.id, destination, status: "PENDING" as const }))).returning({ id: publications.id }); await tx.insert(outboxEvents).values(created.map(publication => ({ topic: "publication.requested", aggregateId: offer.id, payload: { publicationId: publication.id } }))); } return offer; })
};
