import { useEffect, useState } from "react";
import { Link } from "react-router";
import { Footer, Header, OfferCard } from "../../shell/components";
import type { Offer } from "../../catalog/types";
import { apiRequest } from "../../../api/client";

type Profile = { name: string | null; email: string; emailVerifiedAt: string | null };
export default function Account() {
  const [profile, setProfile] = useState<Profile | null>(null); const [offers, setOffers] = useState<Offer[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { Promise.all([apiRequest<{ data: Profile }>("/me"), apiRequest<{ data: Array<{ offer: Offer }> }>("/me/favorites")]).then(([me, favorites]) => { setProfile(me.data); setOffers(favorites.data.map((favorite) => favorite.offer)); }).catch((error) => setMessage(error instanceof Error ? error.message : "Não foi possível carregar sua conta.")); }, []);
  const removeAccount = async () => { if (!window.confirm("Excluir sua conta e anonimizar seus dados? Esta ação não pode ser desfeita.")) return; try { await apiRequest("/me", { method: "DELETE" }); setProfile(null); setOffers([]); setMessage("Sua conta foi excluída e seus dados de perfil foram anonimizados."); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível excluir sua conta."); } };
  return <><Header /><main className="mx-auto max-w-[1600px] px-4 py-16 sm:px-6 lg:px-8"><p className="mb-3 font-mono text-[10px] tracking-[.1em] text-ink/70">SUA CONTA</p><h1 className="mb-9 font-display text-[clamp(44px,5vw,58px)] font-bold leading-[.96] tracking-[-.06em]">Seu radar,<br /><em className="text-brand">do seu jeito.</em></h1>{message ? <section className="max-w-[500px] border-l-4 border-brand bg-[#fff0e7] p-5"><p>{message}</p><Link className="mt-3 inline-block text-xs font-extrabold text-brand" to="/entrar">Entrar ou criar conta</Link></section> : profile && <><section className="flex max-w-[590px] items-center gap-3.5 rounded-[10px] border border-line bg-pine-soft p-5"><div className="grid h-[52px] w-[52px] shrink-0 place-items-center rounded-full bg-brand font-display text-[22px] font-bold text-white">{(profile.name ?? profile.email).slice(0, 1).toUpperCase()}</div><div><strong className="block text-sm">{profile.name ?? "Visitante Promimi"}</strong><span className="mt-1 block text-xs">{profile.email}</span><small className="mt-1 block text-[10px] font-bold text-[#37806a]">{profile.emailVerifiedAt ? "E-mail confirmado" : "Confirme o e-mail enviado para ativar todos os recursos"}</small></div></section><section className="pt-14"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="mb-3 font-mono text-[10px] tracking-[.1em] text-ink/70">OFERTAS GUARDADAS</p><h2 className="font-display text-[34px] font-bold leading-[.95] tracking-[-.05em]">Seus favoritos</h2></div><Link className="text-[13px] font-extrabold text-brand" to="/buscar">Explorar mais →</Link></div>{offers.length ? <div className="grid gap-[18px] md:grid-cols-3">{offers.map((offer) => <OfferCard key={offer.id} offer={offer} />)}</div> : <div className="rounded-[10px] border border-dashed border-[#d6d0c6] p-12 text-center"><h2 className="font-display text-[26px] font-bold">Seu radar está livre</h2><p className="mt-3 text-[13px] text-ink/60">Favorite uma oferta para encontrá-la aqui depois.</p><Link className="mt-3 inline-block text-xs font-extrabold text-brand" to="/buscar">Ver ofertas</Link></div>}</section><section className="mt-16 flex max-w-[700px] flex-col items-start justify-between gap-5 border-t border-line pt-7 sm:flex-row sm:items-end"><div><p className="mb-3 font-mono text-[10px] tracking-[.1em] text-ink/70">PRIVACIDADE</p><h2 className="font-display text-[27px] font-bold">Excluir minha conta</h2><p className="mt-3 max-w-[470px] text-[13px] leading-relaxed text-ink/60">Anonimiza o perfil, remove o acesso e preserva somente o que a legislação exige.</p></div><button className="whitespace-nowrap rounded-md border border-[#e4aaa5] bg-white px-3 py-2.5 text-xs font-extrabold text-danger" onClick={() => void removeAccount()}>Excluir conta</button></section></>}</main><Footer /></>;
}
