FROM node:22-alpine AS build
RUN corepack enable
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile=false && pnpm --filter @promimi/site build
CMD ["pnpm", "--filter", "@promimi/site", "start"]
