import { Link } from "react-router";
import { Footer, Header, OfferCard } from "../../shell/components";
import { apiOffers } from "../server";

const categories = [["Tecnologia", "⌁", "bg-[#edf3ff]"], ["Casa", "⌂", "bg-[#fff0e7]"], ["Moda", "⌘", "bg-[#f4ecff]"], ["Beleza", "✦", "bg-[#ffeef0]"], ["Mercado", "◉", "bg-[#eff6db]"], ["Esporte", "↗", "bg-[#e1f4ec]"]] as const;
export const meta = () => [{ title: "Promimi — promoções que valem a pena" }, { name: "description", content: "Ofertas verificadas, cupons e preços em reais." }];
export async function loader() { return { offers: await apiOffers() }; }

export default function Home({ loaderData }: { loaderData: { offers: Awaited<ReturnType<typeof apiOffers>> } }) {
  const [hero, ...rest] = loaderData.offers;
  return <><Header /><main className="mx-auto max-w-[1600px] px-4 sm:px-6 lg:px-8">
    <section className="relative isolate flex min-h-[508px] items-center overflow-hidden bg-[#d9efe5] px-8 py-16 before:absolute before:-right-36 before:-top-36 before:-z-10 before:h-[600px] before:w-[600px] before:rounded-full before:bg-[repeating-radial-gradient(circle,transparent_0_27px,#b7e1d2_29px_31px)] sm:px-12 lg:px-16">
      <div className="max-w-[640px]"><p className="mb-3 font-mono text-[10px] tracking-[.1em] text-ink/70">GARIMPO DO DIA <span className="text-brand">•</span> ATUALIZADO AGORA</p><h1 className="font-display text-[clamp(44px,6vw,78px)] font-bold leading-[.98] tracking-[-.065em]">Preço baixo não<br /><em className="text-brand">faz barulho.</em></h1><p className="my-6 max-w-[410px] text-[17px] leading-relaxed text-[#4e554f]">A gente procura, confere e deixa só o que realmente vale seu clique.</p><Link className="inline-flex items-center gap-10 rounded-lg bg-brand px-5 py-4 text-sm font-extrabold text-white shadow-[4px_4px_0_#d04d14]" to="/buscar">Ver ofertas de hoje <span className="text-xl">↓</span></Link><div className="mt-9 flex flex-wrap gap-3 text-[11px] font-bold text-[#316653]"><span>✓ preços conferidos</span><span>✓ lojas conhecidas</span><span>✓ sem pegadinha</span></div></div>
      <div className="absolute bottom-9 right-[12%] grid h-48 w-48 rotate-[11deg] place-content-center rounded-full bg-brand text-center text-white shadow-[9px_9px_0_#bfe2d4] max-sm:bottom-4 max-sm:right-5 max-sm:scale-75"><div className="absolute inset-2.5 rounded-full border border-dashed border-white pt-3 font-mono text-[8px] tracking-[.11em]">MELHORES PREÇOS • MELHORES PREÇOS •</div><strong className="font-display text-base leading-[.8]">até<br /><b className="text-[49px]">70%</b><br />off</strong><small className="mt-2 font-mono text-[9px] leading-tight">achados pela<br />nossa equipe</small></div>
    </section>
    <section className="border-b border-line py-14 sm:py-18"><p className="mb-3 font-mono text-[10px] tracking-[.1em] text-ink/70">VÁ DIRETO AO PONTO</p><div className="grid grid-cols-3 gap-2 sm:grid-cols-6">{categories.map(([name, icon, tone]) => <Link key={name} to={`/buscar?categoria=${name.toLowerCase()}`} className={`flex min-h-25 flex-col justify-between rounded-[10px] border border-line p-4 text-[13px] font-extrabold transition hover:-translate-y-1 hover:shadow-[0_8px_0_#e8e3d9] ${tone}`}><span className="text-[29px]">{icon}</span>{name}<b className="self-end text-brand">→</b></Link>)}</div></section>
    {hero && <section className="py-14 sm:py-20"><SectionHeading label="NÃO DEIXE PASSAR" title="O achado da vez" link={`/oferta/${hero.slug}`} text="Abrir oferta →" /><OfferCard offer={hero} featured /></section>}
    <section className="border-t border-line py-14 sm:py-20"><SectionHeading label="ACABOU DE ENTRAR" title="Recém-encontradas" link="/buscar" text="Ver todas →" /><div className="grid gap-[18px] md:grid-cols-3">{rest.map((offer) => <OfferCard key={offer.id} offer={offer} />)}</div></section>
    <section className="-mx-4 grid gap-3 bg-ink px-4 py-14 text-white sm:-mx-6 sm:grid-cols-[1.2fr_1fr] sm:px-6 lg:-mx-8 lg:px-8"><div><p className="mb-3 font-mono text-[10px] tracking-[.1em] text-white/60">SEU RADAR DE DESCONTOS</p><h2 className="font-display text-[clamp(32px,4vw,54px)] font-bold leading-[.98] tracking-[-.06em]">As boas chegam<br /><em className="text-brand">antes no seu e-mail.</em></h2></div><form className="flex h-12 self-center"><input className="w-full border-0 p-3 text-ink outline-none" aria-label="Seu e-mail" type="email" placeholder="seuemail@exemplo.com" /><button className="border-0 bg-brand px-4 font-extrabold" type="submit">Quero receber</button></form><p className="text-[11px] text-white/65 sm:col-start-2">Sem spam. Só preço que merece atenção.</p></section>
  </main><Footer /></>;
}

function SectionHeading({ label, title, link, text }: { label: string; title: string; link?: string; text?: string }) {
  return <div className="mb-7 flex items-end justify-between gap-4"><div><p className="mb-3 font-mono text-[10px] tracking-[.1em] text-ink/70">{label}</p><h2 className="font-display text-[34px] font-bold leading-[.95] tracking-[-.05em]">{title}</h2></div>{link && <Link className="text-[13px] font-extrabold text-brand" to={link}>{text}</Link>}</div>;
}
