import { Form, Link } from "react-router";
import { Footer, Header, OfferCard } from "../../shell/components";
import { apiOffers } from "../server";

export async function loader({ request }: { request: Request }) {
  const url = new URL(request.url);
  const q = url.searchParams.get("q") ?? ""; const store = url.searchParams.get("store") ?? ""; const category = url.searchParams.get("categoria") ?? url.searchParams.get("category") ?? ""; const min = url.searchParams.get("min") ?? ""; const max = url.searchParams.get("max") ?? "";
  const query = new URLSearchParams(); if (q) query.set("q", q); if (store) query.set("store", store); if (category) query.set("category", category); if (min) query.set("min", min); if (max) query.set("max", max);
  return { q, store, category, min, max, offers: await apiOffers(query.size ? `?${query}` : "") };
}
export default function Search({ loaderData }: { loaderData: Awaited<ReturnType<typeof loader>> }) { return <><Header/><main className="search-page"><p className="eyebrow">CATÁLOGO PROMIMI</p><h1>{loaderData.q ? <>Resultados para “{loaderData.q}”</> : <>Ofertas para <em>seu radar.</em></>}</h1><Form method="get" className="catalog-filter"><input name="q" defaultValue={loaderData.q} placeholder="Buscar uma oferta"/><select name="store" defaultValue={loaderData.store}><option value="">Todas as lojas</option><option value="amazon">Amazon</option><option value="mercado-livre">Mercado Livre</option><option value="shopee">Shopee</option></select><input name="min" type="number" min="0" defaultValue={loaderData.min} placeholder="Preço mínimo"/><input name="max" type="number" min="0" defaultValue={loaderData.max} placeholder="Preço máximo"/><button>Aplicar filtros</button></Form><div className="filter-row"><Link to="/buscar" className={!loaderData.category ? "active" : ""}>Tudo</Link>{["tecnologia", "casa", "moda", "beleza", "mercado", "esporte"].map((category) => <Link key={category} className={loaderData.category === category ? "active" : ""} to={`/buscar?categoria=${category}`}>{category}</Link>)}</div><p className="result-count">{loaderData.offers.length} ofertas verificadas</p><div className="offer-grid">{loaderData.offers.length ? loaderData.offers.map((offer) => <OfferCard key={offer.id} offer={offer}/>) : <div className="empty-catalog"><h2>Nenhuma oferta com esses filtros</h2><p>Remova um filtro ou volte ao catálogo completo.</p><Link to="/buscar">Limpar filtros</Link></div>}</div></main><Footer/></>; }
