import { useEffect, useState } from "react";
import { Link } from "react-router";
const api = `${import.meta.env.VITE_API_URL ?? "http://localhost:3001"}/api/v1`;
type Comment = { id: string; body: string; createdAt: string; author: string };
async function request(path: string, init: RequestInit = {}) { const token = typeof window === "undefined" ? null : window.localStorage.getItem("promimi_token"); const response = await fetch(`${api}${path}`, { ...init, headers: { "content-type": "application/json", ...(token ? { authorization: `Bearer ${token}` } : {}), ...init.headers } }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message ?? "Não foi possível concluir esta ação."); return payload; }
export function OfferActions({ offerId }: { offerId: string }) { const [comments, setComments] = useState<Comment[]>([]); const [message, setMessage] = useState(""); const [text, setText] = useState(""); const [loading, setLoading] = useState(false); const [reporting, setReporting] = useState<string | null>(null); const [reason, setReason] = useState(""); useEffect(() => { request(`/offers/${offerId}/comments`).then((data) => setComments(data.data)).catch(() => undefined); }, [offerId]);
  const favorite = async () => { try { await request(`/offers/${offerId}/favorite`, { method: "POST" }); setMessage("Oferta salva nos seus favoritos."); } catch { setMessage("Entre na sua conta para favoritar esta oferta."); } };
  const comment = async (event: React.FormEvent) => { event.preventDefault(); if (!text.trim()) return; setLoading(true); try { const data = await request(`/offers/${offerId}/comments`, { method: "POST", body: JSON.stringify({ body: text }) }); setComments((items) => [{ ...data.data, author: "Você" }, ...items]); setText(""); setMessage("Comentário publicado."); } catch { setMessage("Entre na sua conta para comentar."); } finally { setLoading(false); } };
  const report = async (event: React.FormEvent) => { event.preventDefault(); if (!reporting) return; try { await request(`/comments/${reporting}/report`, { method: "POST", body: JSON.stringify({ reason }) }); setReporting(null); setReason(""); setMessage("Denúncia enviada para a equipe."); } catch { setMessage("Entre na sua conta para denunciar este comentário."); } };
  return <section className="community"><div className="community-head"><div><p className="section-label">CONVERSA SOBRE ESTA OFERTA</p><h2>Tem alguma informação útil?</h2></div><button className="favorite-button" onClick={favorite}>♡ Favoritar</button></div>{message && <p className="action-message">{message} {message.startsWith("Entre") && <Link to="/entrar">Entrar agora</Link>}</p>}<form className="comment-form" onSubmit={comment}><textarea value={text} onChange={(event) => setText(event.target.value)} maxLength={1500} placeholder="Compartilhe sua experiência com esta oferta…"/><button disabled={loading}>{loading ? "Publicando…" : "Publicar comentário"}</button></form><div className="comment-list">{comments.length ? comments.map((item) => <article key={item.id}><div className="comment-avatar">{item.author.slice(0, 1).toUpperCase()}</div><div><strong>{item.author}</strong><time>{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(item.createdAt))}</time><p>{item.body}</p><button onClick={() => setReporting(item.id)}>Denunciar</button>{reporting === item.id && <form className="report-form" onSubmit={report}><select value={reason} onChange={(event) => setReason(event.target.value)} required><option value="">Escolha o motivo</option><option value="Spam ou propaganda">Spam ou propaganda</option><option value="Ofensa ou assédio">Ofensa ou assédio</option><option value="Informação enganosa">Informação enganosa</option></select><button>Enviar denúncia</button><button type="button" onClick={() => setReporting(null)}>Cancelar</button></form>}</div></article>) : <p className="no-comments">Ainda não há comentários. Seja a primeira pessoa a compartilhar uma dica.</p>}</div></section>; }
