import type { FormEventHandler, ReactNode } from "react";
import { BrandLockup } from "./BrandLockup.js";
import { Card } from "./Surface.js";
import { Button } from "./Button.js";
import { ThemeToggle } from "./Theme.js";

export function AdminLoginLayout({ children, error, onSubmit, pending }: { children: ReactNode; error?: string; onSubmit: FormEventHandler<HTMLFormElement>; pending: boolean }) {
  return <main className="relative grid min-h-screen place-items-center bg-mist p-4 sm:p-8"><ThemeToggle className="absolute right-5 top-5" /><div className="grid w-full max-w-[1120px] overflow-hidden rounded-[30px] border border-line bg-paper shadow-[0_20px_58px_rgba(28,35,52,.08)] md:grid-cols-[1.05fr_.95fr]"><section className="hidden min-h-[600px] flex-col justify-between bg-[var(--ui-shell)] p-9 md:flex"><BrandLockup href="/" size="lg" /><div><span className="inline-flex items-center gap-1.5 rounded-full bg-pine-soft px-2.5 py-1 text-[11px] font-semibold text-pine"><span className="h-1.5 w-1.5 rounded-full bg-current opacity-75" />Painel operacional</span><h1 className="mt-5 max-w-sm text-[42px] font-semibold leading-[1.03] tracking-[-.06em] text-ink">Boas decisões começam com uma operação clara.</h1><p className="mt-5 max-w-sm text-sm leading-7 text-ink/58">Gerencie ofertas, integrações e automações em um ambiente protegido.</p></div><p className="text-xs text-ink/42">Promimi · acesso restrito à equipe</p></section><Card className="rounded-none border-0 p-6 shadow-none sm:p-9"><h2 className="text-2xl font-semibold tracking-[-.04em]">Entrar no painel</h2><p className="mt-2 text-sm leading-6 text-ink/55">Use sua conta de administradora ou editora.</p><form className="mt-7 grid gap-4" onSubmit={onSubmit}>{children}{error && <p className="rounded-[14px] border border-danger/15 bg-danger-soft px-3.5 py-3 text-sm text-danger">{error}</p>}<Button className="mt-1 w-full" size="lg" disabled={pending}>{pending ? "Entrando…" : "Entrar com segurança"}</Button></form></Card></div></main>;
}
