import { useState, type ReactNode } from "react";
import { BrandLockup } from "./BrandLockup.js";
import { Button } from "./Button.js";
import { Icon } from "./Icon.js";
import { Input } from "./FormControls.js";
import { Sheet } from "./Overlay.js";

const navigation = [{ href: "/buscar", label: "Explorar" }, { href: "/conta", label: "Minha conta" }];

export function PublicHeader() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <header className="sticky top-0 z-30 bg-[#f3f4f6]/90 px-3 pt-3 backdrop-blur sm:px-5"><div className="mx-auto flex h-[62px] max-w-[1600px] items-center gap-3 rounded-[22px] border border-white bg-white/90 px-3 shadow-[0_4px_15px_rgba(34,42,57,.055)] sm:px-4"><BrandLockup size="sm" /><nav className="ml-4 hidden items-center gap-1 rounded-xl bg-surface-subtle/85 p-1 md:flex">{navigation.map((item) => <a key={item.href} className="rounded-[12px] px-3 py-1.5 text-[11px] font-medium text-ink/65 transition hover:bg-white hover:text-ink" href={item.href}>{item.label}</a>)}</nav><form action="/buscar" className="ml-auto hidden w-[min(330px,28vw)] items-center gap-2 rounded-[14px] border border-line/80 bg-[#fafbfc] px-3 md:flex"><Icon name="search" className="h-3.5 w-3.5 text-ink/40" /><Input className="min-h-0 flex-1 border-0 bg-transparent px-0 py-2.5 text-xs shadow-none focus:ring-0" name="q" placeholder="Buscar ofertas" /><button className="text-xs font-semibold text-brand" type="submit">Buscar</button></form><span aria-label="Notificações" className="ml-auto hidden h-9 w-9 place-items-center rounded-[14px] bg-surface-subtle/85 text-ink/55 sm:grid md:ml-0"><Icon name="bell" /></span><a href="/entrar" className="hidden min-h-8 items-center gap-2 rounded-[14px] bg-brand px-3 text-[11px] font-semibold text-white shadow-[0_5px_12px_rgba(238,77,45,.17)] transition hover:bg-brand-dark sm:inline-flex md:ml-0"><Icon name="users" className="h-3.5 w-3.5" />Entrar</a><Button variant="subtle" size="sm" className="ml-auto md:hidden" onClick={() => setMenuOpen(true)}>Menu</Button></div><Sheet open={menuOpen} onClose={() => setMenuOpen(false)} title="Navegação" description="Encontre ofertas e gerencie sua conta."><nav className="grid gap-2">{navigation.map((item) => <a key={item.href} onClick={() => setMenuOpen(false)} className="rounded-[14px] px-4 py-3 text-sm font-medium hover:bg-mist" href={item.href}>{item.label}</a>)}<a onClick={() => setMenuOpen(false)} className="rounded-[14px] bg-brand px-4 py-3 text-sm font-semibold text-white" href="/entrar">Entrar</a></nav></Sheet></header>;
}

export function PublicFooter() {
  return <footer className="px-3 pb-3 pt-8 sm:px-5"><div className="mx-auto grid max-w-[1600px] grid-cols-2 gap-8 rounded-[22px] border border-white bg-white px-5 py-10 text-xs shadow-[0_3px_12px_rgba(34,42,57,.04)] sm:px-6 md:grid-cols-[2fr_1fr_1fr]"><div className="col-span-2 md:col-span-1"><BrandLockup size="sm" /><p className="mt-4 max-w-[265px] leading-6 text-ink/55">Ofertas boas, apresentadas com clareza para você decidir sem perder tempo.</p></div><div className="flex flex-col gap-3 text-ink/55"><strong className="mb-1 text-ink">Promimi</strong><a href="/buscar">Ofertas</a><a href="/entrar">Minha conta</a></div><div className="flex flex-col gap-3 text-ink/55"><strong className="mb-1 text-ink">Transparência</strong><a href="/privacidade">Privacidade</a><a href="/termos">Termos de uso</a><a href="/cookies">Cookies</a></div><p className="col-span-2 border-t border-line pt-6 leading-6 text-ink/50 md:col-span-3">Alguns links podem render comissão, sem custo adicional para você.</p></div></footer>;
}

export function CommerceHero({ offerCount }: { offerCount: number }) {
  return <section className="grid gap-4"><section className="relative overflow-hidden rounded-[18px] border border-white bg-white p-5 shadow-[0_2px_8px_rgba(34,42,57,.055)] sm:p-7 lg:p-8"><div className="absolute -right-14 -top-16 h-52 w-52 rounded-full bg-brand/10 blur-3xl" /><div className="relative flex flex-wrap items-start justify-between gap-5"><div className="max-w-2xl"><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-1.5 rounded-full bg-pine-soft px-2.5 py-1 text-[11px] font-semibold text-pine"><span className="h-1.5 w-1.5 rounded-full bg-current opacity-75" />Preço monitorado</span><span className="text-[11px] text-ink/45">Atualizações a cada nova verificação</span></div><h1 className="mt-5 text-[clamp(34px,4.5vw,54px)] font-semibold leading-[1.03] tracking-[-.065em]">Encontre a oferta certa, <span className="text-brand">sem correr atrás.</span></h1><p className="mt-4 max-w-xl text-sm leading-7 text-ink/58">Preço, cupom e loja conferidos antes de aparecerem no seu radar. Você decide com mais contexto e menos ruído.</p><a href="/buscar" className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-[16px] bg-brand px-5 text-sm font-semibold text-white shadow-[0_7px_16px_rgba(238,77,45,.19)] transition hover:bg-brand-dark"><Icon name="search" />Explorar ofertas</a></div><div className="grid min-w-[220px] gap-3 sm:grid-cols-2 lg:w-[330px] lg:grid-cols-1"><div className="rounded-[16px] bg-surface-subtle/75 p-4"><span className="grid h-8 w-8 place-items-center rounded-xl bg-brand-soft text-brand"><Icon name="tag" /></span><strong className="mt-4 block text-[28px] leading-none tracking-[-.06em]">{offerCount}</strong><span className="mt-1.5 block text-[11px] text-ink/52">ofertas publicadas</span></div><div className="rounded-[16px] border border-line/70 bg-white p-4"><span className="grid h-8 w-8 place-items-center rounded-xl bg-pine-soft text-pine"><Icon name="activity" /></span><strong className="mt-4 block text-sm">Verificação clara</strong><span className="mt-1.5 block text-[11px] leading-5 text-ink/52">Mostramos preço, condição e loja antes do clique.</span></div></div></div></section></section>;
}

export function CommerceCollection({ children }: { children: ReactNode }) {
  return <section className="mt-8"><div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[.12em] text-ink/42">Em destaque</p><h2 className="mt-1 text-2xl font-semibold tracking-[-.04em]">Ofertas para aproveitar agora</h2></div><a className="text-sm font-semibold text-brand transition hover:text-brand-dark" href="/buscar">Ver catálogo →</a></div>{children}</section>;
}

export function CommerceOfferGrid({ children }: { children: ReactNode }) {
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{children}</div>;
}

export type CommerceOfferCardProps = { href: string; category: string; store: string; title: string; price: string; originalPrice?: string; discount?: string; coupon?: string; tone?: "warm" | "green" | "blue" | "violet" };
export function CommerceOfferCard({ href, category, store, title, price, originalPrice, discount, coupon, tone = "blue" }: CommerceOfferCardProps) {
  const tones = { warm: "bg-[#fff4f0]", green: "bg-pine-soft", blue: "bg-info-soft", violet: "bg-[#f4efff]" };
  return <section className="group min-w-0 overflow-hidden rounded-[18px] border border-white bg-white shadow-[0_2px_8px_rgba(34,42,57,.055)] transition duration-200 hover:-translate-y-0.5 hover:shadow-[0_14px_30px_rgba(28,35,52,.09)]"><div className={`relative min-h-[180px] overflow-hidden p-4 ${tones[tone]}`}><span className="inline-flex items-center gap-1.5 rounded-full bg-surface-subtle px-2.5 py-1 text-[11px] font-semibold text-ink/62"><span className="h-1.5 w-1.5 rounded-full bg-current opacity-75" />{category}</span><div className="absolute bottom-[12%] right-[15%] h-36 w-36 rotate-[-13deg] rounded-[30px] border-[14px] border-white/70 shadow-[inset_0_0_0_14px_rgba(42,49,65,.07)]" /></div><div className="p-5"><div className="flex items-center justify-between gap-3 text-xs text-ink/50"><span className="font-medium">{store}</span>{discount && <span className="rounded-full bg-amber-soft px-2.5 py-1 text-[11px] font-semibold text-amber">-{discount}</span>}</div><h3 className="mt-3 min-h-[42px] text-[15px] font-semibold leading-[1.4] tracking-[-.018em]"><a className="transition hover:text-brand" href={href}>{title}</a></h3><div className="mt-4 flex items-baseline gap-2">{originalPrice && <del className="text-xs text-ink/42">{originalPrice}</del>}<strong className="text-[23px] font-semibold tracking-[-.055em]">{price}</strong></div>{coupon ? <div className="mt-4 flex items-center gap-2 rounded-[14px] border border-dashed border-brand/40 bg-brand-soft px-2.5 py-2 text-brand"><small className="text-[9px] font-semibold uppercase tracking-wide">Cupom</small><code className="text-[11px] font-bold">{coupon}</code></div> : <span className="mt-4 block text-[11px] font-medium text-pine">● Preço verificado agora</span>}<a className="mt-4 flex items-center justify-between border-t border-line/75 pt-3.5 text-xs font-semibold text-ink/70 transition hover:text-brand" href={href}>Ver oferta <span>→</span></a></div></section>;
}
