import { useEffect, useState } from "react";
import { Link } from "react-router";
import { Footer, Header, OfferCard } from "../components";
import type { Offer } from "@promimi/contracts";
import { apiRequest } from "../lib/api-client";

const accountRequest = apiRequest;
type Profile = { name: string | null; email: string; emailVerifiedAt: string | null };
export default function Account() { const [profile, setProfile] = useState<Profile | null>(null); const [offers, setOffers] = useState<Offer[]>([]); const [message, setMessage] = useState(""); useEffect(() => { Promise.all([accountRequest<{ data: Profile }>("/me"), accountRequest<{ data: Array<{ offer: Offer }> }>("/me/favorites")]).then(([me, favorites]) => { setProfile(me.data); setOffers(favorites.data.map((favorite) => favorite.offer)); }).catch((error) => setMessage(error instanceof Error ? error.message : "Não foi possível carregar sua conta.")); }, []); const removeAccount = async () => { if (!window.confirm("Excluir sua conta e anonimizar seus dados? Esta ação não pode ser desfeita.")) return; try { await accountRequest("/me", { method: "DELETE" }); setProfile(null); setOffers([]); setMessage("Sua conta foi excluída e seus dados de perfil foram anonimizados."); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível excluir sua conta."); } };
  return <><Header/><main className="account-page"><p className="eyebrow">SUA CONTA</p><h1>Seu radar,<br/><em>do seu jeito.</em></h1>{message ? <section className="account-note"><p>{message}</p><Link to="/entrar">Entrar ou criar conta</Link></section> : profile && <><section className="account-summary"><div className="account-avatar">{(profile.name ?? profile.email).slice(0, 1).toUpperCase()}</div><div><strong>{profile.name ?? "Visitante Promimi"}</strong><span>{profile.email}</span><small>{profile.emailVerifiedAt ? "E-mail confirmado" : "Confirme o e-mail enviado para ativar todos os recursos"}</small></div></section><section className="account-favorites"><div className="section-heading"><div><p className="section-label">OFERTAS GUARDADAS</p><h2>Seus favoritos</h2></div><Link to="/buscar">Explorar mais →</Link></div>{offers.length ? <div className="offer-grid">{offers.map((offer) => <OfferCard key={offer.id} offer={offer}/>)}</div> : <div className="empty-catalog"><h2>Seu radar está livre</h2><p>Favorite uma oferta para encontrá-la aqui depois.</p><Link to="/buscar">Ver ofertas</Link></div>}</section><section className="danger-zone"><div><p className="section-label">PRIVACIDADE</p><h2>Excluir minha conta</h2><p>Anonimiza o perfil, remove o acesso e preserva somente o que a legislação exige.</p></div><button onClick={() => void removeAccount()}>Excluir conta</button></section></>}</main><Footer/></>; }
