import { useState } from "react";
import { Header } from "../components";
import { Link } from "react-router";
import { apiRequest } from "../lib/api-client";

export default function Login() {
  const [create, setCreate] = useState(false); const [notice, setNotice] = useState("");
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { email: String(form.get("email")), password: String(form.get("password")), ...(create ? { name: String(form.get("name")) } : {}) }; try { await apiRequest(`/auth/${create ? "register" : "login"}`, { method: "POST", body: JSON.stringify(payload) }); setNotice(create ? "Conta criada. Confira seu e-mail para confirmar o acesso." : "Você entrou. Já pode favoritar e comentar."); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível entrar."); } };
  return <><Header/><main className="auth-page"><div><p className="eyebrow">SUA CONTA PROMIMI</p><h1>Guarde o que<br/><em>vale a pena.</em></h1><p>Favorite ofertas, acompanhe seus achados e participe com respeito nos comentários.</p></div><form className="auth-card" onSubmit={submit}><h2>{create ? "Criar conta" : "Entrar"}</h2>{create && <label>Nome<input required name="name" minLength={2} placeholder="Como podemos chamar você?"/></label>}<label>E-mail<input required name="email" type="email" placeholder="voce@exemplo.com"/></label><label>Senha<input required name="password" type="password" minLength={10} placeholder="No mínimo 10 caracteres"/></label><button>{create ? "Criar minha conta" : "Entrar na minha conta"}</button>{notice && <p className="auth-notice">{notice}</p>}<Link className="recover-link" to="/recuperar-acesso">Esqueci minha senha</Link><hr/><p>{create ? "Já tem conta?" : "Ainda não tem conta?"} <button type="button" className="link-button" onClick={() => setCreate(!create)}>{create ? "Entrar" : "Criar conta grátis"}</button></p></form></main></>;
}
