import { relations } from "drizzle-orm";
import { boolean, index, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

const id = () => uuid("id").defaultRandom().primaryKey();
const dates = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };

export const role = pgEnum("user_role", ["ADMIN", "EDITOR", "VISITOR"]);
export const offerStatus = pgEnum("offer_status", ["DRAFT", "PUBLISHED", "EXPIRED", "PAUSED"]);
export const publicationStatus = pgEnum("publication_status", ["PENDING", "SENT", "FAILED", "PAUSED"]);
export const tokenPurpose = pgEnum("token_purpose", ["EMAIL_VERIFICATION", "PASSWORD_RESET"]);
export const executionStatus = pgEnum("execution_status", ["QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "PAUSED"]);

export const users = pgTable("users", { id: id(), email: varchar("email", { length: 320 }).notNull().unique(), passwordHash: text("password_hash").notNull(), name: varchar("name", { length: 120 }), role: role("role").default("VISITOR").notNull(), emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }), totpSecretEncrypted: text("totp_secret_encrypted"), totpEnabled: boolean("totp_enabled").default(false).notNull(), deletedAt: timestamp("deleted_at", { withTimezone: true }), ...dates });
export const authTokens = pgTable("auth_tokens", { id: id(), userId: uuid("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(), purpose: tokenPurpose("purpose").notNull(), tokenHash: varchar("token_hash", { length: 128 }).notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("auth_tokens_user_purpose_idx").on(t.userId, t.purpose)]);
export const categories = pgTable("categories", { id: id(), name: varchar("name", { length: 80 }).notNull(), slug: varchar("slug", { length: 100 }).notNull().unique(), description: text("description"), isActive: boolean("is_active").default(true).notNull(), ...dates });
export const stores = pgTable("stores", { id: id(), name: varchar("name", { length: 100 }).notNull(), slug: varchar("slug", { length: 120 }).notNull().unique(), domain: varchar("domain", { length: 255 }), logoUrl: text("logo_url"), isActive: boolean("is_active").default(true).notNull(), ...dates });
export const offers = pgTable("offers", { id: id(), slug: varchar("slug", { length: 180 }).notNull().unique(), title: varchar("title", { length: 240 }).notNull(), description: text("description"), imageUrl: text("image_url"), storeId: uuid("store_id").references(() => stores.id).notNull(), categoryId: uuid("category_id").references(() => categories.id), currentPrice: numeric("current_price", { precision: 12, scale: 2 }).notNull(), originalPrice: numeric("original_price", { precision: 12, scale: 2 }), discountPercent: integer("discount_percent"), couponCode: varchar("coupon_code", { length: 64 }), affiliateUrl: text("affiliate_url").notNull(), sourceUrl: text("source_url"), status: offerStatus("status").default("DRAFT").notNull(), verifiedAt: timestamp("verified_at", { withTimezone: true }), expiresAt: timestamp("expires_at", { withTimezone: true }), publishedAt: timestamp("published_at", { withTimezone: true }), createdById: uuid("created_by_id").references(() => users.id), ...dates }, (t) => [index("offers_status_published_idx").on(t.status, t.publishedAt), index("offers_store_idx").on(t.storeId)]);
export const favorites = pgTable("favorites", { id: id(), userId: uuid("user_id").references(() => users.id).notNull(), offerId: uuid("offer_id").references(() => offers.id).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [uniqueIndex("favorites_user_offer_idx").on(t.userId, t.offerId)]);
export const comments = pgTable("comments", { id: id(), offerId: uuid("offer_id").references(() => offers.id).notNull(), userId: uuid("user_id").references(() => users.id).notNull(), body: text("body").notNull(), isHidden: boolean("is_hidden").default(false).notNull(), ...dates });
export const reports = pgTable("reports", { id: id(), commentId: uuid("comment_id").references(() => comments.id).notNull(), reporterId: uuid("reporter_id").references(() => users.id).notNull(), reason: varchar("reason", { length: 300 }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const integrations = pgTable("integrations", { id: id(), provider: varchar("provider", { length: 60 }).notNull().unique(), enabled: boolean("enabled").default(false).notNull(), credentialsEncrypted: text("credentials_encrypted"), settings: jsonb("settings").default({}), lastHealthAt: timestamp("last_health_at", { withTimezone: true }), ...dates });
export const routines = pgTable("routines", { id: id(), name: varchar("name", { length: 120 }).notNull(), enabled: boolean("enabled").default(false).notNull(), scheduleCron: varchar("schedule_cron", { length: 80 }).default("0 * * * *").notNull(), filters: jsonb("filters").default({}), destinations: jsonb("destinations").default([]), dailyLimit: integer("daily_limit").default(100).notNull(), ...dates });
export const routineExecutions = pgTable("routine_executions", { id: id(), routineId: uuid("routine_id").references(() => routines.id, { onDelete: "cascade" }).notNull(), status: executionStatus("status").default("QUEUED").notNull(), startedAt: timestamp("started_at", { withTimezone: true }), finishedAt: timestamp("finished_at", { withTimezone: true }), foundCount: integer("found_count").default(0).notNull(), acceptedCount: integer("accepted_count").default(0).notNull(), duplicateCount: integer("duplicate_count").default(0).notNull(), rejectedCount: integer("rejected_count").default(0).notNull(), error: text("error"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("routine_executions_routine_created_idx").on(t.routineId, t.createdAt)]);
export const publications = pgTable("publications", { id: id(), offerId: uuid("offer_id").references(() => offers.id).notNull(), destination: varchar("destination", { length: 80 }).notNull(), status: publicationStatus("status").default("PENDING").notNull(), attempts: integer("attempts").default(0).notNull(), externalId: varchar("external_id", { length: 200 }), error: text("error"), sentAt: timestamp("sent_at", { withTimezone: true }), ...dates });
export const clicks = pgTable("clicks", { id: id(), offerId: uuid("offer_id").references(() => offers.id).notNull(), source: varchar("source", { length: 100 }).default("direct").notNull(), fingerprint: varchar("fingerprint", { length: 128 }), isFiltered: boolean("is_filtered").default(false).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (t) => [index("clicks_offer_created_idx").on(t.offerId, t.createdAt)]);

export const offersRelations = relations(offers, ({ one, many }) => ({ store: one(stores, { fields: [offers.storeId], references: [stores.id] }), category: one(categories, { fields: [offers.categoryId], references: [categories.id] }), comments: many(comments), favorites: many(favorites), publications: many(publications), clicks: many(clicks) }));
export const commentsRelations = relations(comments, ({ one }) => ({ offer: one(offers, { fields: [comments.offerId], references: [offers.id] }), user: one(users, { fields: [comments.userId], references: [users.id] }) }));
export const favoritesRelations = relations(favorites, ({ one }) => ({ offer: one(offers, { fields: [favorites.offerId], references: [offers.id] }), user: one(users, { fields: [favorites.userId], references: [users.id] }) }));
export const publicationsRelations = relations(publications, ({ one }) => ({ offer: one(offers, { fields: [publications.offerId], references: [offers.id] }) }));
export const clicksRelations = relations(clicks, ({ one }) => ({ offer: one(offers, { fields: [clicks.offerId], references: [offers.id] }) }));
export const authTokensRelations = relations(authTokens, ({ one }) => ({ user: one(users, { fields: [authTokens.userId], references: [users.id] }) }));
export const routineExecutionsRelations = relations(routineExecutions, ({ one }) => ({ routine: one(routines, { fields: [routineExecutions.routineId], references: [routines.id] }) }));
export const routinesRelations = relations(routines, ({ many }) => ({ routineExecutions: many(routineExecutions) }));
