import { useState } from "react";
import { Link } from "react-router";
import { Header } from "../../shell/components";
import { apiRequest } from "../../../api/client";

export default function Login() {
  const [create, setCreate] = useState(false); const [notice, setNotice] = useState("");
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const payload = { email: String(form.get("email")), password: String(form.get("password")), ...(create ? { name: String(form.get("name")) } : {}) }; try { await apiRequest(`/auth/${create ? "register" : "login"}`, { method: "POST", body: JSON.stringify(payload) }); setNotice(create ? "Conta criada. Confira seu e-mail para confirmar o acesso." : "Você entrou. Já pode favoritar e comentar."); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível entrar."); } };
  return <><Header /><main className="grid min-h-[calc(100vh-88px)] items-center gap-10 bg-[linear-gradient(105deg,#d9efe5_0_55%,#fffdf8_55%)] px-4 py-14 sm:px-6 md:grid-cols-[1fr_420px] md:px-8 lg:px-12 xl:px-20"><div><p className="mb-3 font-mono text-[10px] tracking-[.1em] text-ink/70">SUA CONTA PROMIMI</p><h1 className="font-display text-[clamp(48px,5vw,58px)] font-bold leading-[.98] tracking-[-.065em]">Guarde o que<br /><em className="text-brand">vale a pena.</em></h1><p className="mt-6 max-w-[380px] leading-relaxed text-ink/70">Favorite ofertas, acompanhe seus achados e participe com respeito nos comentários.</p></div><form className="rounded-xl border border-line bg-white p-8 shadow-[12px_12px_0_#cde4da]" onSubmit={submit}><h2 className="font-display text-[34px] font-bold leading-[.95] tracking-[-.05em]">{create ? "Criar conta" : "Entrar"}</h2>{create && <label className="mt-5 grid gap-1.5 text-xs font-bold">Nome<input className="rounded-md border border-[#d7d2c9] p-3" required name="name" minLength={2} placeholder="Como podemos chamar você?" /></label>}<label className="mt-5 grid gap-1.5 text-xs font-bold">E-mail<input className="rounded-md border border-[#d7d2c9] p-3" required name="email" type="email" placeholder="voce@exemplo.com" /></label><label className="mt-5 grid gap-1.5 text-xs font-bold">Senha<input className="rounded-md border border-[#d7d2c9] p-3" required name="password" type="password" minLength={10} placeholder="No mínimo 10 caracteres" /></label><button className="my-5 w-full cursor-pointer rounded-md bg-brand p-3 font-extrabold text-white" type="submit">{create ? "Criar minha conta" : "Entrar na minha conta"}</button>{notice && <p className="rounded-md bg-pine-soft p-2.5 text-xs leading-relaxed text-pine">{notice}</p>}<Link className="text-xs font-bold text-brand" to="/recuperar-acesso">Esqueci minha senha</Link><hr className="mt-6 border-0 border-t border-line" /><p className="mt-4 text-xs text-ink/65">{create ? "Já tem conta?" : "Ainda não tem conta?"} <button type="button" className="cursor-pointer border-0 bg-transparent p-0 font-extrabold text-brand" onClick={() => setCreate(!create)}>{create ? "Entrar" : "Criar conta grátis"}</button></p></form></main></>;
}
